import {
  angular,
  astro,
  aws,
  azure,
  bash,
  bootstrap,
  capacitorjs,
  c,
  csharp,
  cpp,
  css,
  dart,
  django,
  docker,
  expo,
  express,
  fastapi,
  figma,
  firebase,
  flask,
  framer,
  flutter,
  flutterflow,
  gcp,
  git,
  go,
  html,
  ionic,
  java,
  js,
  kotlin,
  kubernetes,
  laravel,
  linux,
  mongo,
  nest,
  next,
  node,
  nuxt,
  php,
  psql,
  python,
  pytorch,
  react,
  remixjs,
  ruby,
  rust,
  solidity,
  shopify,
  springboot,
  supabase,
  svelte,
  swift,
  tailwind,
  tensorflow,
  ts,
  vue,
  webassembly,
  wordpress
} from '../assets'

export const TECH_STACK_CONFIG = [
  { name: 'angular', icon: angular },
  { name: 'astro', icon: astro },
  { name: 'aws', icon: aws },
  { name: 'azure', icon: azure },
  { name: 'bash', icon: bash },
  { name: 'bootstrap', icon: bootstrap },
  { name: 'c#', icon: csharp },
  { name: 'c++', icon: cpp },
  { name: 'c', icon: c },
  { name: 'capacitor', icon: capacitorjs },
  { name: 'css', icon: css },
  { name: 'dart', icon: dart },
  { name: 'django', icon: django },
  { name: 'docker', icon: docker },
  { name: 'expo', icon: expo },
  { name: 'express', icon: express },
  { name: 'fastapi', icon: fastapi },
  { name: 'figma', icon: figma },
  { name: 'firebase', icon: firebase },
  { name: 'flask', icon: flask },
  { name: 'framer', icon: framer },
  { name: 'flutter', icon: flutter },
  { name: 'flutterflow', icon: flutterflow },
  { name: 'google cloud platform', icon: gcp },
  { name: 'git', icon: git },
  { name: 'golang', icon: go },
  { name: 'html', icon: html },
  { name: 'ionic', icon: ionic },
  { name: 'java', icon: java },
  { name: 'javascript', icon: js },
  { name: 'kotlin', icon: kotlin },
  { name: 'kubernetes', icon: kubernetes },
  { name: 'laravel', icon: laravel },
  { name: 'linux', icon: linux },
  { name: 'mongodb', icon: mongo },
  { name: 'nest', icon: nest },
  { name: 'next', icon: next },
  { name: 'nuxt', icon: nuxt },
  { name: 'node', icon: node },
  { name: 'php', icon: php },
  { name: 'postgresql', icon: psql },
  { name: 'python', icon: python },
  { name: 'pytorch', icon: pytorch },
  { name: 'react', icon: react },
  { name: 'remixjs', icon: remixjs },
  { name: 'ruby', icon: ruby },
  { name: 'rust', icon: rust },
  { name: 'shopify', icon: shopify },
  { name: 'springboot', icon: springboot },
  { name: 'solidity', icon: solidity },
  { name: 'supabase', icon: supabase },
  { name: 'svelte', icon: svelte },
  { name: 'swift', icon: swift },
  { name: 'tailwind', icon: tailwind },
  { name: 'tensorflow', icon: tensorflow },
  { name: 'typescript', icon: ts },
  { name: 'vue', icon: vue },
  { name: 'webassembly', icon: webassembly },
  { name: 'wordpress', icon: wordpress }
].sort((a, b) => a.name.localeCompare(b.name))
